var Mock = require('mockjs')
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, '10.20.250.32', () => console.log(`Server startup success, listening on port ${port}!`))

//-------------------- rest --------------------
//根据运单号获取两个电话号码 (为实名使用)
app.post('/rest/oms.waybill.mail.getPersonPhone', function (req, res) {
    // res.send('Hello World!')

        var data = Mock.mock({
            "code": 0,
            "msg": "OK",
            "data": {
              "orderPickup": {
                "orderMobile": /^1[385][1-9]\d{8}/,
                "orderPhone": /\d{3,4}\-\d{8}/,
                "contactPhone": /^1[385][1-9]\d{8}/
              }
            },
            "traceId": "@guid"
          })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//网点代码查询
app.post('/rest/baseconfig.point.getNodeInfoByIds', function (req, res) {

    var data = Mock.mock({
        "code": 0,
        "msg": "OK",
        "data": [{
          "ids": [],
          "pointId": "",
          "nodeName": "福永中转场五六栋",
          "nodeAttrib": "10",
          "nodeType": "20",
          "actualNodeType": "",
          "pointParentId": "",
          "departmentId": "1",
          "departmentCode": "0755",
          "cityId": "XZ2-229",
          "cityCode": "0755",
          "regionCode": "10",
          "drawable": "20",
          "woodenSetable": "20",
          "pointCode": "755ZK",
          "nodeCode": "WD1811-0118",
          "departmentNo": "755C7",
          "incharge": "",
          "telphone": "",
          "longitude": 113.808935,
          "latitude": 22.670649,
          "remark": "",
          "auditor": "",
          "auditTime": null,
          "operatable": "",
          "provinceId": "XZ1-31",
          "countyId": "XZ3-1572",
          "townId": "XZ4-028381",
          "addressDetail": "广东省深圳市宝安区福永街道和平社区深翔物流园五六栋",
          "auditStatus": "",
          "roadId": "XZ5-0697699",
          "inchargeId": "",
          "organizationId": "11449",
          "districtCode": "",
          "districtChangeTime": null,
          "boundSurfaceId": "",
          "fenceCode": "",
          "nodeGroups": [],
          "fenceChangeTime": null,
          "airportNames": [],
          "airportId": "",
          "pickupSned": "",
          "nodeSplitList": [],
          "provinceList": [],
          "longitudeAndLatitudeList": [],
          "pointConfigInfoOperation": {},
          "startAirport": "",
          "endAirportId": "",
          "endAirport": "",
          "transferName": "",
          "addressDetailAll": "广东省深圳市宝安区福永街道和平社区广东省深圳市宝安区福永街道和平社区深翔物流园五六栋",
          "pointName": "",
          "departmentName": "跨越集团",
          "nodeGroup": "",
          "nodeNames": [],
          "province": "广东省",
          "city": "深圳市",
          "county": "宝安区",
          "town": "福永街道",
          "road": "和平社区",
          "parentNodetData": {},
          "areaSynData": {},
          "regionName": "",
          "nodeGroupCode": "",
          "nodeGroupName": "",
          "legalType": "10",
          "id": "1064791871197352028",
          "traceId": "9abcc8c341ceacd0ca5195a16b42129c",
          "createdBy": "1064364282976735239",
          "creationDate": 1543396517000,
          "updatedBy": "1024574654094839808",
          "updationDate": 1544085493000,
          "enabledFlag": 1
        }],
        "traceId": "c32776cbf789a2fae3543fcc9980b68c"
      }, {
        "code": 0,
        "msg": "OK",
        "data": [{
          "ids": [],
          "pointId": "",
          "nodeName": "厦门殿前二级中转场",
          "nodeAttrib": "10",
          "nodeType": "30",
          "actualNodeType": "",
          "pointParentId": "1068505272935321641",
          "departmentId": "11782",
          "departmentCode": "0592",
          "cityId": "",
          "cityCode": "0592",
          "regionCode": "20",
          "drawable": "20",
          "woodenSetable": "",
          "pointCode": "592WA",
          "nodeCode": "WD1812-0041",
          "departmentNo": "592C",
          "incharge": "",
          "telphone": "",
          "longitude": 113.428361,
          "latitude": 23.617342,
          "remark": "",
          "auditor": "",
          "auditTime": null,
          "operatable": "10",
          "provinceId": "",
          "countyId": "",
          "townId": "",
          "addressDetail": "",
          "auditStatus": "",
          "roadId": "",
          "inchargeId": "",
          "organizationId": "11795",
          "districtCode": "",
          "districtChangeTime": null,
          "boundSurfaceId": "",
          "fenceCode": "",
          "nodeGroups": [],
          "fenceChangeTime": null,
          "airportNames": [],
          "airportId": "",
          "pickupSned": "",
          "nodeSplitList": [],
          "provinceList": [],
          "longitudeAndLatitudeList": [],
          "pointConfigInfoOperation": {},
          "startAirport": "",
          "endAirportId": "",
          "endAirport": "",
          "transferName": "",
          "addressDetailAll": "广东省广州市从化区鳌头镇鳌头社区",
          "pointName": "",
          "departmentName": "高崎机场一级分拨区",
          "nodeGroup": "",
          "nodeNames": [],
          "province": "广东省",
          "city": "广州市",
          "county": "从化区",
          "town": "鳌头镇",
          "road": "鳌头社区",
          "parentNodetData": {
            "ids": [],
            "pointId": "",
            "nodeName": "清江新下塘点部",
            "nodeAttrib": "10",
            "nodeType": "40",
            "actualNodeType": "",
            "pointParentId": "",
            "departmentId": "11776",
            "departmentCode": "0595",
            "cityId": "XZ2-130",
            "cityCode": "0595",
            "regionCode": "20",
            "drawable": "20",
            "woodenSetable": "",
            "pointCode": "595CA",
            "nodeCode": "WD1812-0035",
            "departmentNo": "595C",
            "incharge": "",
            "telphone": "",
            "longitude": null,
            "latitude": null,
            "remark": "",
            "auditor": "",
            "auditTime": null,
            "operatable": "",
            "provinceId": "XZ1-31",
            "countyId": "",
            "townId": "",
            "addressDetail": "",
            "auditStatus": "",
            "roadId": "",
            "inchargeId": "",
            "organizationId": "11778",
            "districtCode": "",
            "districtChangeTime": null,
            "boundSurfaceId": "",
            "fenceCode": "",
            "nodeGroups": [],
            "fenceChangeTime": null,
            "airportNames": [],
            "airportId": "",
            "pickupSned": "",
            "nodeSplitList": [],
            "provinceList": [],
            "longitudeAndLatitudeList": [],
            "pointConfigInfoOperation": {},
            "startAirport": "",
            "endAirportId": "",
            "endAirport": "",
            "transferName": "",
            "addressDetailAll": "",
            "pointName": "",
            "departmentName": "清江操作部",
            "nodeGroup": "",
            "nodeNames": [],
            "province": "广东省",
            "city": "江门市",
            "county": "",
            "town": "",
            "road": "",
            "parentNodetData": {},
            "areaSynData": {},
            "regionName": "华南",
            "nodeGroupCode": "",
            "nodeGroupName": "",
            "legalType": "00",
            "id": "1068505272935321641",
            "traceId": "9e3790f6820a3ac907d67ad7e8efb37a",
            "createdBy": "1069418581360447493",
            "creationDate": 1544082401000,
            "updatedBy": "1069418581360447493",
            "updationDate": 1544082401000,
            "enabledFlag": 1
          },
          "areaSynData": {},
          "regionName": "华南",
          "nodeGroupCode": "",
          "nodeGroupName": "",
          "legalType": "00",
          "id": "1070613431518826500",
          "traceId": "579c96e17faa73ee65c2340e236211fe",
          "createdBy": "1069418581360447493",
          "creationDate": 1544090351000,
          "updatedBy": "1024574654094839808",
          "updationDate": 1544091205000,
          "enabledFlag": 1
        }],
        "traceId": "8ff47ecfda6dd0349ae59e514eb6a8c7"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//实名认证检测
app.post('/rest/crm.customerMail.auth.check', function (req, res) {

    var data = Mock.mock({
        "code": "0",
        "msg": "OK",
        "data": {
          "id": /\d{5}/,
          "authFlag|1": ["10", "20"],
          "useType|1-2": 1,
          "billSource|1-7": 1,
          "operCode|1-2": 1,
          "customerId": /\d{3,5}/,
          "companyNo": /\d{9,11}/,
          "userCardType|1": ["01", "02", "03", "04", "05", "06", "07", "08", "09"],
          "contactN": "@cname",
          "idCard": "@id",
          "gender|1-2": 1,
          "collectMethod|1": ["10", "20", "30", "40", "50", "99"],
          "contactWay": "手机",
          "contactNumber": /^1[385][1-9]\d{8}/,
          "addressType|1-2": 1,
          "mobileNo": /^1[385][1-9]\d{8}/,
          "userType|1-2": 1,
          "userTypeStatus|1": ["10", "20"],
          "iCName": "@cword(5,8)公司",
          "orgNo": "@natural",
          "creditCode": "@natural",
          "taxRegNo": "@natural",
          "linkMobile": /^1[385][1-9]\d{8}/,
          "agent": "@cname",
          "street": "@county(true)测试路305号",
          "regAddress": "@county(true)测试路777号",
          "province": "广东省",
          "provinceId": "XZ1-31",
          "city": "深圳市",
          "cityId": "XZ2-229",
          "district": "宝安区",
          "districtId|1": ["XZ3-0459", "XZ3-0752", "XZ3-1308", "XZ3-1478", "XZ3-1570", "XZ3-1596", "XZ3-1770", "XZ3-2485", "XZ3-2549", "XZ3-2624"]
        },
        "success": true,
        "traceId": "@guid"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//外部运力查询
app.post('/rest/ecs.zc.driver.erp.findDriverInfoByDriverName.do', function (req, res) {

    var data = Mock.mock({
        "code": 200,
        "msg": "未知异常",
        "data": [{
          "id": '@id',
          "identityNumber": '@id',
          "inOffice|1": ["10", "20"],
          "name": "@cname()",
          "networkName|1": ["@cword(3,5)中转场", "@cword(3, 5)点部"],
          "companyMobile": /^1[38569][1-9]\d{8}/,
          "privateMobile": /^1[38569][1-9]\d{8}/
        }],
        "view": 0,
        "success": false
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//HR-get
app.post('/rest/hr.remoteEmployee.get', function (req, res) {

    var data = Mock.mock({
        "code": 0,
        "msg": "OK",
        "data": {
          "name": "杨子易",
          "inOffice": 10,
          "officeStatus": 10,
          "dutyId": "279",
          "duty": "测试工程师",
          "lastDuty": "",
          "dutyCode": "",
          "infomationType": 10,
          "employingUnit": "",
          "laborType": null,
          "employeeArea": "10",
          "departmentId": "11115",
          "department": "深圳测试部",
          "departmentCode": "",
          "higherDepartmentId": "11112",
          "higherDepartment": "跨越新科技",
          "leaderId": "1064354171734528001",
          "leader": "煮面师傅",
          "leaderRankCode": "",
          "inductionDate": 1541001600000,
          "trialPeriod": "10",
          "arrivalDate": 1543593600000,
          "lastArrivalDate": null,
          "personnelType": 30,
          "education": null,
          "employeeNumber": "000848",
          "icNumber": "110#",
          "locatioinCity": "深圳",
          "privateMobile": "15013445658",
          "companyMobile": "17722450983",
          "shortPhone": "",
          "qq": "",
          "rankCode": "/10/1,001,000,000,0000,0000,0000,0008,0000//E,1.3,T1.3,0005/000848/000848",
          "sex": 10,
          "national": "560",
          "nativePlace": "汉",
          "maritalStatus": 40,
          "identityType": 10,
          "identityNumber": "420982199210130093",
          "identityMaturityDate": 7981084800000,
          "birthday": 718905600000,
          "birthdayFlag": "",
          "companyLive": null,
          "identityAddress": "宝安区星航华府",
          "currentAddress": "宝安区星航华府",
          "positiveDate": 1543593600000,
          "actualPositiveDate": 1543507200000,
          "emergencyContact": "1100",
          "relationship": "50",
          "contactNumber": "",
          "employmentType": 10,
          "internshipDate": 1543507200000,
          "nationality": 10,
          "email": "",
          "mainBody": "",
          "trialDate": null,
          "trainingDate": null,
          "politicsStatus": 10,
          "physicalCondition": 40,
          "webchat": "",
          "phone": "",
          "nativeType": 10,
          "identityIssuingDate": null,
          "jobYeas": null,
          "englishLevel": null,
          "professionalLanguage": "",
          "qualificationCertificate": "",
          "criminalRecord": null,
          "developDirection": null,
          "skills": "",
          "applyJob": "",
          "personalInterviewerId": "",
          "personalInterviewer": "",
          "jobInterviewerId": "",
          "jobInterviewer": "",
          "interviewerOpinion": "",
          "introduce": null,
          "introducerId": "",
          "introducer": "",
          "relation": "",
          "introduceDeptId": "",
          "introduceDept": "",
          "introduceDutyId": "",
          "introduceDuty": "",
          "departureType": null,
          "applyDate": null,
          "reason": "",
          "departureDate": null,
          "liability": null,
          "interviewRecord": "",
          "ext1": null,
          "ext2": null,
          "ext3": "",
          "ext4": "",
          "age": 26,
          "seniority": 0,
          "traceId": "",
          "salaryArea": "",
          "remark": "",
          "networkId": "11115",
          "networkName": "深圳测试部",
          "departmentRoute": "",
          "departmentInfo": {
            "name": "深圳测试部",
            "chargeId": "1024574654094839808",
            "partTimeFlag": 20,
            "chargeName": "超级管理员",
            "dutyId": "19",
            "dutyName": "副董事长",
            "chargeHierarchy": "",
            "departmentDuty": "1",
            "departmentPosition": "1",
            "parentName": "跨越新科技",
            "hierarchy": "80",
            "hierarchyCode": null,
            "departmentCode": "1,001,000,000,0000,0000,0000,0008,0000",
            "departmentCodeList": [],
            "departmentRoute": "跨越集团/深圳测试部",
            "virtualDepartment": 10,
            "instructions": "",
            "children": [],
            "fuzzyValue": "",
            "nameFilterEx": [],
            "appFlag": "",
            "recordById": "",
            "recordBy": "",
            "names": [],
            "planningStaffNum": 1,
            "employeeNum": 90,
            "reason": "",
            "togetherFlag": "",
            "changeList": [],
            "ids": [],
            "code": "department_code",
            "parentId": "11112",
            "displayIndex": null,
            "left": 1337,
            "right": 1358,
            "level": 8,
            "id": "11115",
            "traceId": "4aa8bde34ca556b32b904af8d58f6d66",
            "createdBy": "1024574654094839808",
            "creationDate": 1542599087000,
            "updatedBy": "1064364156442972161",
            "updationDate": 1543028188000,
            "enabledFlag": 1
          },
          "concurrentDepartmentList": [],
          "dutyInfo": {
            "name": "测试工程师",
            "code": "E,1.3,T1.3,0005",
            "hierarchy": "E",
            "level": "E",
            "rank": "1.3",
            "grade": "员工级",
            "sequence": "T",
            "postRank": "助理专员Ⅲ",
            "instructions": "测试",
            "sequenceCode": "T1.3",
            "dutySn": "E,1.3,T1.3",
            "id": "279",
            "traceId": "e91de25d5b0f791c890c23749c5c5175",
            "createdBy": "1024574654094839808",
            "creationDate": 1542594640000,
            "updatedBy": "1024574654094839808",
            "updationDate": 1542594640000,
            "enabledFlag": 1
          },
          "educationInfo": {},
          "shortPhoneArea": "",
          "certificate": {},
          "contract": {},
          "archivesList": [],
          "photoUrl": "",
          "fileList": [],
          "departureStatus": null,
          "messageFlag": null,
          "specialDepartmentFlag": "",
          "ministry": "",
          "dept": "",
          "section": "",
          "office": "",
          "group": "",
          "ids": [],
          "names": [],
          "employeeNumbers": [],
          "dutyIds": [],
          "nameFuzzy": null,
          "nameEqualFlag": "",
          "departmentIds": [],
          "networkIds": [],
          "departments": [],
          "departmentFuzzy": "",
          "departmentNotContain": [],
          "dutyNotContain": [],
          "identityNumbers": [],
          "managerId": "",
          "manager": "",
          "mobile": "",
          "emergecyMobile": "",
          "mobiles": [],
          "month": "",
          "goodsTime": null,
          "nameOrNumber": "",
          "isLeaved": "",
          "subsidiaryDepartment": "",
          "leaderAndClerkFlag": "",
          "dataFlag": "",
          "leaderFlag": "",
          "departureDateBegin": null,
          "departureDateEnd": null,
          "id": "1068412249459200009",
          "createdBy": "1024574654094839808",
          "creationDate": 1543564600000,
          "updatedBy": "1024574654094839808",
          "updationDate": 1543571968000,
          "enabledFlag": 1
        },
        "traceId": "65e215b8b0092d44db981bbb9146c84a"
      }, {
        "code": 0,
        "msg": "OK",
        "data": {
          "name": "向南",
          "inOffice": 10,
          "officeStatus": 10,
          "dutyId": "279",
          "duty": "测试工程师",
          "lastDuty": "",
          "dutyCode": "",
          "infomationType": 10,
          "employingUnit": "",
          "laborType": null,
          "employeeArea": "40",
          "departmentId": "1",
          "department": "跨越集团",
          "departmentCode": "",
          "higherDepartmentId": "0",
          "higherDepartment": "",
          "leaderId": "1064365653234880512",
          "leader": "向阳",
          "leaderRankCode": "",
          "inductionDate": 1541001600000,
          "trialPeriod": "10",
          "arrivalDate": 1543593600000,
          "lastArrivalDate": null,
          "personnelType": 30,
          "education": null,
          "employeeNumber": "000134",
          "icNumber": "",
          "locatioinCity": "深圳",
          "privateMobile": "18770069156",
          "companyMobile": "",
          "shortPhone": "",
          "qq": "",
          "rankCode": "京津冀@深圳@@向阳@跨越集团@测试工程师",
          "sex": 20,
          "national": "",
          "nativePlace": "",
          "maritalStatus": null,
          "identityType": 10,
          "identityNumber": "360428199502036521",
          "identityMaturityDate": 1575043200000,
          "birthday": 791740800000,
          "birthdayFlag": "",
          "companyLive": null,
          "identityAddress": "深圳",
          "currentAddress": "深圳",
          "positiveDate": 1543593600000,
          "actualPositiveDate": null,
          "emergencyContact": "",
          "relationship": "",
          "contactNumber": "",
          "employmentType": 10,
          "internshipDate": null,
          "nationality": null,
          "email": "",
          "mainBody": "",
          "trialDate": null,
          "trainingDate": null,
          "politicsStatus": null,
          "physicalCondition": null,
          "webchat": "",
          "phone": "",
          "nativeType": 10,
          "identityIssuingDate": null,
          "jobYeas": null,
          "englishLevel": null,
          "professionalLanguage": "",
          "qualificationCertificate": "",
          "criminalRecord": null,
          "developDirection": null,
          "skills": "",
          "applyJob": "",
          "personalInterviewerId": "",
          "personalInterviewer": "",
          "jobInterviewerId": "",
          "jobInterviewer": "",
          "interviewerOpinion": "",
          "introduce": null,
          "introducerId": "",
          "introducer": "",
          "relation": "",
          "introduceDeptId": "",
          "introduceDept": "",
          "introduceDutyId": "",
          "introduceDuty": "",
          "departureType": null,
          "applyDate": null,
          "reason": "",
          "departureDate": null,
          "liability": null,
          "interviewRecord": "",
          "ext1": null,
          "ext2": null,
          "ext3": "",
          "ext4": "",
          "age": 23,
          "seniority": 0,
          "traceId": "",
          "salaryArea": "",
          "remark": "",
          "networkId": "1",
          "networkName": "跨越集团",
          "departmentRoute": "",
          "departmentInfo": {
            "name": "跨越集团",
            "chargeId": "1049991332735553536",
            "partTimeFlag": null,
            "chargeName": "胡海建",
            "dutyId": "282",
            "dutyName": "董事长",
            "chargeHierarchy": "A,7.2,M6.2,0008",
            "departmentDuty": "人工智能",
            "departmentPosition": "干物流的",
            "parentName": "",
            "hierarchy": "10",
            "hierarchyCode": null,
            "departmentCode": "1",
            "departmentCodeList": [],
            "departmentRoute": "跨越集团",
            "virtualDepartment": 10,
            "instructions": "开发",
            "children": [],
            "fuzzyValue": "",
            "nameFilterEx": [],
            "appFlag": "",
            "recordById": "",
            "recordBy": "",
            "names": [],
            "planningStaffNum": null,
            "employeeNum": 15,
            "subDepartmentNum": null,
            "reason": "",
            "togetherFlag": "",
            "changeList": [],
            "ids": [],
            "code": "department_code",
            "parentId": "0",
            "displayIndex": null,
            "left": 1,
            "right": 1370,
            "level": 1,
            "id": "1",
            "traceId": "16284d0c6bdf2e1fa09cf48faeb475b3",
            "createdBy": "System",
            "creationDate": 1537440731000,
            "updatedBy": "1024574654094839808",
            "updationDate": 1539173672000,
            "enabledFlag": 1
          },
          "concurrentDepartmentList": [],
          "dutyInfo": {
            "name": "测试工程师",
            "code": "E,1.3,T1.3,0005",
            "hierarchy": "E",
            "level": "E",
            "rank": "1.3",
            "grade": "员工级",
            "sequence": "T",
            "postRank": "助理专员Ⅲ",
            "instructions": "测试",
            "sequenceCode": "T1.3",
            "dutySn": "E,1.3,T1.3",
            "id": "279",
            "traceId": "e91de25d5b0f791c890c23749c5c5175",
            "createdBy": "1024574654094839808",
            "creationDate": 1542594640000,
            "updatedBy": "1024574654094839808",
            "updationDate": 1542594640000,
            "enabledFlag": 1
          },
          "educationInfo": {},
          "shortPhoneArea": "",
          "certificate": {},
          "contract": {},
          "archivesList": [],
          "photoUrl": "",
          "fileList": [],
          "departureStatus": null,
          "messageFlag": null,
          "specialDepartmentFlag": "",
          "ministry": "",
          "dept": "",
          "section": "",
          "office": "",
          "group": "",
          "recruitSource": null,
          "needSalary": null,
          "locationProvince": "",
          "locationArea": "",
          "locationId": "",
          "nativePlaceId": "",
          "ids": [],
          "names": [],
          "employeeNumbers": [],
          "dutyIds": [],
          "nameFuzzy": null,
          "nameEqualFlag": "",
          "departmentIds": [],
          "networkIds": [],
          "departments": [],
          "departmentFuzzy": "",
          "departmentNotContain": [],
          "dutyNotContain": [],
          "identityNumbers": [],
          "managerId": "",
          "manager": "",
          "mobile": "",
          "emergecyMobile": "",
          "mobiles": [],
          "month": "",
          "goodsTime": null,
          "nameOrNumber": "",
          "isLeaved": "",
          "subsidiaryDepartment": "",
          "leaderAndClerkFlag": "",
          "dataFlag": "",
          "leaderFlag": "",
          "departureDateBegin": null,
          "departureDateEnd": null,
          "id": "1065070771152424962",
          "createdBy": "1024574654094839808",
          "creationDate": 1542767741000,
          "updatedBy": "1024574654094839808",
          "updationDate": 1544001561000,
          "enabledFlag": 1
        },
        "traceId": "883760c7f5e2b74e004252eb9d5ae117"
      },
       {
        "code": 0,
        "msg": "OK",
        "data": {
          "name": "朱洪成",
          "inOffice": 10,
          "officeStatus": 10,
          "dutyId": "281",
          "duty": "组长",
          "infomationType": 10,
          "employingUnit": "",
          "employeeArea": "20",
          "departmentId": "11179",
          "department": "福田益田点部",
          "higherDepartmentId": "11126",
          "higherDepartment": "深圳操作部",
          "leaderId": "1066158076172767238",
          "leader": "陈坤才",
          "inductionDate": 1509552000000,
          "arrivalDate": 1512057600000,
          "employeeNumber": "000297",
          "icNumber": "",
          "locatioinCity": "深圳市",
          "privateMobile": "13537562358",
          "companyMobile": "1357845784",
          "shortPhone": "",
          "qq": "",
          "rankCode": "城市区号/20/1,009,000,038,0000,0000,0000,0000,0000//D,2.2,M1.2,0007/000297/000297,000273",
          "sex": 10,
          "identityNumber": "431109198501252365",
          "identityAddress": "湖南省永州市冷水滩区",
          "positiveDate": 1512057600000,
          "email": "",
          "webchat": "",
          "phone": "",
          "departureDate": null,
          "age": 33,
          "seniority": 1,
          "salaryArea": "",
          "remark": "",
          "networkId": "11179",
          "networkName": "福田益田点部",
          "departmentInfo": {
            "chargeId": "1066158076172767238",
            "chargeName": "陈坤才",
            "hierarchy": "40",
            "departmentRoute": "跨越集团/福田益田点部"
          },
          "dutyInfo": {
            "hierarchy": "D",
            "rank": "2.2",
            "sequence": "M"
          },
          "shortPhoneArea": "",
          "certificate": {
            "level": 60,
            "roadTransportCertificate": 10,
            "vehicleLevel": 30
          },
          "contract": {},
          "photoUrl": "",
          "id": "1066228390554570754"
        },
        "traceId": "bf8e138dbc48bf8768edf33401d07921"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//查询运单详情
app.get('/rest/oms.waybill.mail.listByWaybillNumbers', function (req, res) {

    var data = Mock.mock({
        "code": 0,
        "msg": "OK",
        "data": [{
          "waybillNumber": /\d{11}/,
          "serviceMode": "",
          "upload": {
            "operateBy": "",
            "operateByName": ""
          },
          "recordDelivery": {
            "operateBy": "",
            "operateByName": ""
          },
          "record": {
            "operateBy": "",
            "operateByName": ""
          },
          "waybillGoods": {
            "count|1-100": 100,
            "goodsType": "@cword(2,5)",
            "productCode": "",
            "pickupTime": "@datetime"
          },
          "waybillFinance": {
            "customerPayMode": "",
            "freightWeight": "",
            "insuranceValue": ""
          },
          "waybillDelivery": {
            "customerId|1-900": 100,
            "customerName": "@cword(5,8)公司",
            "networkId": /\d{5,9}/,
            "network|1": ["龙岗南约点部", "石岩塘头点部", "平湖李朗二级中转场", "福田益田点部", "光明塘尾二级中转场", "平湖布吉点部", "南山西丽点部"],
            "person": "@cname",
            "mobile": /^1[385][1-9]\d{8}/,
            "phone": /\d{3,4}\-\d{8}/,
            "address": "@county(true)",
            "province": "广东省",
            "provinceId": "XZ1-31",
            "city": "深圳市",
            "cityId": "XZ2-229",
            "district": "南山区",
            "districtId|1": ["XZ3-0459", "XZ3-0752", "XZ3-1308", "XZ3-1478", "XZ3-1570", "XZ3-1596", "XZ3-1770", "XZ3-2485", "XZ3-2549", "XZ3-2624"]
          },
          "waybillPickup": {
            "customerId|1-900": 100,
            "customerName": "@cword(5,8)公司",
            "networkId": /\d{5,9}/,
            "network|1": ["盛泽震泽点部", "张家窝文安点部", "金华婺城点部", "顺德宏丰二级中转场", "台州黄岩二级中转场", "福州机场航空", "北仑澥浦点部"],
            "person": "@cname",
            "mobile": /^1[385][1-9]\d{8}/,
            "phone": /\d{3,4}\-\d{8}/,
            "address": "@county(true)",
            "province": "北京",
            "provinceId": "XZ1-06",
            "city": "北京市",
            "cityId": "XZ2-174",
            "district": "平定县",
            "districtId|1": ["XZ3-0097", "XZ3-0104", "XZ3-0246", "XZ3-0412", "XZ3-0524", "XZ3-0538", "XZ3-0554",
              "XZ3-1008", "XZ3-1189", "XZ3-1275", "XZ3-1418", "XZ3-1427", "XZ3-1892", "XZ3-1928", "XZ3-2530", "XZ3-2759"
            ]
          }
        }],
        "traceId": "@guid"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//路由查询
app.get('/rest/tms.route.getBatchExteriorRoute', function (req, res) {

    var data = Mock.mock({
        "code": 0,
        "msg": "OK",
        "data": [{
          "vos": [],
          "waybillNumbers": [],
          "waybillNumber": "77700000198",
          "interiorRouteList": [],
          "exteriorRouteList": [{
            "routeType": "20",
            "serialNumber": 1,
            "waybillNumber": "77700000198",
            "orderNumber": "",
            "routeStep": "10",
            "stepSort": 1,
            "routeDescription": "已安排@cname前往客户处取货，车牌号：面包@cfirstBD45855",
            "unscanCount": null,
            "uploadId": "1066228390554570754",
            "uploadName|1": ["杨子易", "煮面师傅", "向南", "没有员工", "李明"],
            "uploadDate": 1543391650000,
            "uploadPhone": "",
            "nextStation": "客户处",
            "batchNumber": "",
            "destinationAirport": "",
            "flightNumber": "",
            "ladingNumber": "",
            "leaderId": "",
            "leaderName": "",
            "leaderPhone": "",
            "nextStationId": "",
            "location": "",
            "startRouteStep": "",
            "endRouteStep": "",
            "type": "",
            "waybillId": "1067689056322785282",
            "id": "1067689058134724612",
            "traceId": "7e77620b6c24305d",
            "createdBy": "System",
            "creationDate": 1543391883000,
            "updatedBy": "System",
            "updationDate": 1543391883000,
            "enabledFlag": 1
          }, {
            "routeType": "20",
            "serialNumber": 1,
            "waybillNumber": "77700000198",
            "orderNumber": "",
            "routeStep": "20",
            "stepSort": 1,
            "routeDescription": "已安排@cname前往客户处取货，车牌号：面包@cfirstBD45855",
            "unscanCount": null,
            "uploadId": "1066228390554570754",
            "uploadName|1": ["杨子易", "煮面师傅", "向南", "没有员工", "李明"],
            "uploadDate": 1543391650000,
            "uploadPhone": "",
            "nextStation": "客户处",
            "batchNumber": "",
            "destinationAirport": "",
            "flightNumber": "",
            "ladingNumber": "",
            "leaderId": "",
            "leaderName": "",
            "leaderPhone": "",
            "nextStationId": "",
            "location": "",
            "startRouteStep": "",
            "endRouteStep": "",
            "type": "",
            "waybillId": "1067689056322785282",
            "id": "1067689058134724612",
            "traceId": "7e77620b6c24305d",
            "createdBy": "System",
            "creationDate": 1543391883000,
            "updatedBy": "System",
            "updationDate": 1543391883000,
            "enabledFlag": 1
          }],
          "id": "",
          "ids": [],
          "page": 0,
          "pageSize": 10,
          "elasticsearchFlag": "N",
          "countFlag": "N",
          "orderByClauses": [],
          "aggregations": []
        }],
        "traceId": "99756f44a34bfdf2ec9979b233f3ca22"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})


//-------------------- msg --------------------
//运单消息服务
app.post('/msg/tms.waybill.data', function (req, res) {
    // res.send('Hello World!')

        var data = Mock.mock({
            "waybillDelivery": {
              "uploadDeliveryCustomer": "@cword(5,8)公司",
              "customerId|1-900": 100,
              "customerCode": /\d{9,12}/,
              "areaCode": "0755",
              "person": "@cname",
              "mobile": /^1[385][1-9]\d{8}/,
              "phone": /^1[385][1-9]\d{8}/,
              "networkId": "@id",
              "network|1": ["龙岗南约点部", "石岩塘头点部", "平湖李朗二级中转场", "福田益田点部", "光明塘尾二级中转场", "平湖布吉点部", "南山西丽点部"],
              "provinceId": "XZ1-31",
              "province": "@province",
              "cityId": "XZ2-229",
              "city": "@city",
              "districtId|1": ["XZ3-0459", "XZ3-0752", "XZ3-1308", "XZ3-1478", "XZ3-1570", "XZ3-1596", "XZ3-1770", "XZ3-2485", "XZ3-2549", "XZ3-2624"],
              "district": "福田区",
              "address": "@county(true)测试路803号"
            },
            "waybillPickup": {
              "customerId|1-900": 100,
              "customerName": "@cword(5,8)公司",
              "customerCode": /\d{9,12}/,
              "person": "@cname",
              "mobile": /^1[385][1-9]\d{8}/,
              "areaCode": "010",
              "phone": /^1[385][1-9]\d{8}/,
              "networkId": "@id",
              "network|1": ["盛泽震泽点部", "张家窝文安点部", "金华婺城点部", "顺德宏丰二级中转场", "台州黄岩二级中转场", "福州机场航空", "北仑澥浦点部"],
              "provinceId": "XZ1-06",
              "province": "北京",
              "cityId": "XZ2-174",
              "city": "北京市",
              "districtId|1": ["XZ3-0097", "XZ3-0104", "XZ3-0246", "XZ3-0412", "XZ3-0524", "XZ3-0538", "XZ3-0554",
                "XZ3-1008", "XZ3-1189", "XZ3-1275", "XZ3-1418", "XZ3-1427", "XZ3-1892", "XZ3-1928", "XZ3-2530", "XZ3-2759"
              ],
              "district": "平定县",
              "address": "@county(true)测试路A座503号"
            },
            "waybillFinance": {
              "actualWeight": "@float(60, 100,1,2)"
            },
            "waybillGoods": {
              "goodsType": "@cword(2,5)",
              "count|1-100": 100,
              "pickupTime": "@datetime"
            },
            "id": /\d{9,12}/,
            "waybillNumber": /\d{11}/,
            "serviceMode|1": ["10", "20", "30", "40", "50", "60", "70", "80", "90",
              "100", "110", "160", "170", "190", "200", "210", "220", "230", "240", "250", "260"
            ],
            "waybillStatus|1": ["10", "20", "30", "40", "50", "60", "70"],
            "businessAuditStatus|1": ["10", "20", "30", "40", "50", "60", "70"],
            "financeAuditStatus|1": ["10", "30"],
            "updateSource|1": ["10", "20", "30", "40"],
            "updationDate": "@datetime"
          })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//网点代码推送
app.get('/msg/baseconfig.node.sendInfo', function (req, res) {

    var data = Mock.mock({
        "type": "save",
        "saveNode": {
          "id": 1064791871197352028,
          "traceId": null,
          "createdBy": null,
          "creationDate": null,
          "updatedBy": null,
          "updationDate": null,
          "enabledFlag": 1,
          "ids": null,
          "pointId": null,
          "nodeName": "厦门殿前二级中转场",
          "nodeAttrib": "10",
          "nodeType": "30",
          "actualNodeType": null,
          "pointParentId": 1068505272935321600,
          "departmentId": 11782,
          "departmentCode": "0592",
          "cityId": "",
          "cityCode": "0592",
          "regionCode": "20",
          "drawable": "20",
          "woodenSetable": "",
          "pointCode": "592WA",
          "nodeCode": "WD1812-0041",
          "departmentNo": "592C",
          "incharge": "",
          "telphone": null,
          "longitude": 113.428361,
          "latitude": 23.617342,
          "remark": null,
          "auditor": null,
          "auditTime": null,
          "operatable": null,
          "provinceId": "",
          "countyId": "",
          "townId": "",
          "addressDetail": "",
          "auditStatus": null,
          "roadId": "",
          "inchargeId": null,
          "organizationId": 11795,
          "districtCode": null,
          "districtChangeTime": null,
          "boundSurfaceId": null,
          "fenceCode": null,
          "nodeGroups": null,
          "fenceChangeTime": null,
          "airportNames": null,
          "airportId": null,
          "pickupSned": null,
          "nodeSplitList": [],
          "provinceList": null,
          "longitudeAndLatitudeList": null,
          "pointConfigInfoOperation": null,
          "startAirport": null,
          "endAirportId": null,
          "endAirport": null,
          "transferName": null,
          "addressDetailAll": null,
          "pointName": "",
          "departmentName": "高崎机场一级分拨区",
          "nodeGroup": null,
          "nodeNames": null,
          "province": "广东省",
          "city": "广州市",
          "county": "从化区",
          "town": "鳌头镇",
          "road": "鳌头社区",
          "parentNodetData": null,
          "areaSynData": null,
          "regionName": "华南",
          "nodeGroupCode": null,
          "nodeGroupName": null,
          "legalType": "00",
          "parentNodeName": null,
          "parentNodeCode": null
        }
      }, {
        "updatePoint": [{
            "id": 1068505272935321641,
            "traceId": "1725fe65b2315ade1f64fb4cae9c7353",
            "createdBy": null,
            "creationDate": null,
            "updatedBy": "1066892158125019139",
            "updationDate": "2018-12-06 11:45:22",
            "enabledFlag": 1,
            "pointName": null,
            "nodeId": null,
            "pickupDistance": null,
            "sendDistance": null,
            "startAirportId": null,
            "startAirport": null,
            "endAirportId": null,
            "endAirport": null,
            "regionCode": null,
            "sendDepartmentId": null,
            "customerServiceId": null,
            "inchargeId": null,
            "pickupDispatchId": null,
            "sendDispatchId": null,
            "orderAreaId": 1064461736753565700,
            "specialOrderAreaId": null,
            "nodeCode": null,
            "airportAreaId": null,
            "airportArea": null,
            "airportAreaName": null,
            "node1name": null,
            "node2name": null,
            "node3name": null,
            "node4name": null,
            "node5name": null,
            "level": null,
            "pickingAir": null,
            "dataSources": null,
            "pointBack": null,
            "fieldAbnormal": null,
            "organizationId": null,
            "departmentName": null,
            "pointTransferList": null,
            "sendDispatchName": null,
            "orderAreaName": null,
            "specialOrderAreaName": null,
            "dispatchPerson": null,
            "pointConfigInfoOperationList": null,
            "pickupPointConfigInfo": null,
            "sendPointConfigInfo": null,
            "order": null,
            "nodeInfo": null,
            "specialOrder": null,
            "pointConfigInfoOperationInchargeList": null,
            "incharge": null,
            "pointConfigInfoPersonList": null,
            "pointConfigInfoOperationNames": null,
            "customerServiceDepartmentName": null,
            "sendDepartmentName": null,
            "nodeName": null,
            "pickupRegion": null,
            "pickupRegionPersionAll": null,
            "deliveryRegion": null,
            "deliveryRegionPersionAll": null,
            "orderArea": null,
            "orderAreaPersionAll": null,
            "specialOrderArea": null,
            "specialOrderAreaPersionAll": null,
            "orderType": null,
            "dispatchType": null,
            "dispatchPersonId": null,
            "region": null
          },
          {
            "id": 1064791871197352028
          },
          {
            "id": 1064791871197352028
          }
      
        ],
        "type": "update"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//实名认证消息
app.post('/msg/crm.msg.customer.mail', function (req, res) {

    var data = Mock.mock({
        "id": /\d{5}/,
        "useType|1-2": 1,
        "billSource|1-7": 1,
        "operCode|1-2": 1,
        "companyNo": /\d{9,11}/,
        "userCardType|1": ["01", "02", "03", "04", "05", "06", "07", "08", "09"],
        "contactN": "@cname",
        "idCard": "@id",
        "gender|1-2": 1,
        "collectMethod|1": ["10", "20", "30", "40", "50", "99"],
        "contactWay": "手机",
        "contactNumber": /^1[385][1-9]\d{8}/,
        "addressType|1-2": 1,
        "mobileNo": /^1[385][1-9]\d{8}/,
        "userType|1-2": 1,
        "userTypeStatus|1": ["10", "20"],
        "iCName": "@cword(5,8)",
        "orgNo": "@natural",
        "creditCode": "@natural",
        "taxRegNo": "@natural",
        "linkMobile": /^1[385][1-9]\d{8}/,
        "agent": "@cname",
        "street": "@county(true)测试路305号",
        "regAddress": "@county(true)测试路777号",
        "province": "广东省",
        "provinceId": "XZ1-31",
        "city": "深圳市",
        "cityId": "XZ2-229",
        "district": "宝安区",
        "districtId|1": ["XZ3-0459", "XZ3-0752", "XZ3-1308", "XZ3-1478", "XZ3-1570", "XZ3-1596", "XZ3-1770", "XZ3-2485", "XZ3-2549", "XZ3-2624"]
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//外部运力推送
app.get('/msg/ecs.zc.driver.mq.pushDriverInfoToDawk', function (req, res) {

    var data = Mock.mock({
        "id": "248290386944000",
        "name": "许萍",
        "changeType": "update"
      }, {
        "id": "248290386944001",
        "name": "杨子易",
        "changeType": "update"
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//HR推送
app.get('/msg/hr.employee.message', function (req, res) {

    var data = Mock.mock({
        "changeType": "update",
        "businessId": 1069530960555479000
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

//路由推送
app.get('/msg/tms.route.exterior.data', function (req, res) {

    var data = Mock.mock({
        "id|+1": 1,
        "waybillNumber|+1": 90086100066,
        "routeStep|1": ["10", "20"]
      
      })
    res.writeHead(200,{"Content-Type":'application/json','charset':'utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'PUT,POST,GET,DELETE,OPTIONS'});//可以解决跨域的请求
    res.end(JSON.stringify(data));
})

